version: '3.5'

services:

    backend:
      build:
        context: ./backend/backend-example-docker/
      links:
        - redis
      environment:
        - FRONT_URL=http://localhost/
        - REDIS=redis
        - REDIS_PORT=6379
        - DB_USERNAME=postgres
        - DB_PASSWORD=postgres
        - DB_HOST=db
      ports:
        - "8000:8000"
      expose: 
        - "8000"
      depends_on:
        - db

    frontend:
      build:
        context: ./frontend/frontend-example-docker/
      environment:
        - API_URL=http://localhost:8000
      ports:
        - "5000:5000"

    db:
      image: postgres
      restart: unless-stopped
      environment:
        - POSTGRES_PASSWORD=postgres
        - PGDATA=/database
      expose:
        - "5432"
      volumes:
        - postgres:/database

    redis:
        image: redis:latest
        ports:
          - "6379:6379"
        expose:
          - "6379"
        command: ["redis-server", "--appendonly", "yes"]
        volumes:
        - redis-data:/data

    nginx:
      image: nginx
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
      ports:
        - "80:80"
      depends_on:
        - backend

volumes:
  redis-data:
  postgres: