version: '3.5'

services:
  frontend:
    build:
      context: ./ml-kurkkumopo-frontend
    ports:
      - "3000:3000"
    expose:
      - "3000"

  backend:
    build:
      context: ./ml-kurkkumopo-backend
    ports:
      - "5000:5000"
    expose:
      - "5000"
    depends_on:
      - trainer
    volumes:
    - trainer-data:/src/model

  trainer:
    build:
      context: ./ml-kurkkumopo-training
    volumes:
    - trainer-data:/src/data
    - trainer-data:/src/model
    - trainer-data:/src/imgs

volumes:
  trainer-data:
  images: