version: '3.5'

services:
    redis:
        image: redis:latest
        ports:
          - "6379:6379"
        expose:
          - "6379"
        command: ["redis-server", "--appendonly", "yes"]
        volumes:
        - redis-data:/data

    backend:
      build:
        context: ./backend/backend-example-docker/
      links:
        - redis
      environment:
        - FRONT_URL=http://localhost:5000
        - REDIS=redis
        - REDIS_PORT=6379
      command: "npm start"
      ports:
        - "8000:8000"
      expose: 
        - "8000"

    frontend:
      build:
        context: ./frontend/frontend-example-docker/
      environment:
        - API_URL=http://localhost:8000
      command: "serve -s -l 5000 dist"
      ports:
        - "5000:5000"
volumes:
  redis-data: